export const ADD_TO_CART = 'ADD_TO_CART';

export const CHANGE_MSG = 'CHANGE_MESSAGE';

export const DELETE_PRODUCT_ITEM = 'DELETE_PRODUCT_ITEM';

export const INCREASE_PRODUCT_ITEM = 'INCREASE_PRODUCT_ITEM';

export const DECREASE_PRODUCT_ITEM = 'DECREASE_PRODUCT_ITEM';